notifications:
  log:
    enabled: true

  webhooks:
    - name: visionengine
      url: ""                 # {api.url}/notifications/webhook
      enabled: false
      timeout_seconds: 5

    # - name: slack
    #   url: ""
    #   enabled: false
    #   timeout_seconds: 5

    # - name: custom
    #   url: ""
    #   enabled: false
    #   timeout_seconds: 5
